# SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
#
# SPDX-License-Identifier: Apache-2.0

"""Generate C mapping tables for the RainMaker Neo Matter mirror from the declarative JSON mapping.

The library (mapping/lib/*.json) is the single source of truth shared with future
raising-engine consumers: every capability, composite and device-type rule the mirror
knows. A profile (mapping/profiles/*.json) names the device types a product ships, and
this script emits the compiled-in C tables for that selection alone - capabilities and
composites nothing kept references are dropped, so unused vocabulary costs no flash.
"""

import argparse
import json
import sys

GENERATED_BANNER = """/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/* Auto-generated by gen_mapping_table.py from {source} - DO NOT EDIT */
"""

XFORM_TYPES = {
    "identity": "RM_MIRROR_XFORM_IDENTITY",
    "linear": "RM_MIRROR_XFORM_LINEAR",
    "kelvin_mireds": "RM_MIRROR_XFORM_KELVIN_MIREDS",
    "enum_map": "RM_MIRROR_XFORM_ENUM_MAP",
    "string": "RM_MIRROR_XFORM_STRING",
    "scale": "RM_MIRROR_XFORM_SCALE",
}

# Matter-domain value types: the wire type of a mapped attribute, and the TLV width of a
# write_as command argument. RM_MIRROR_VAL_NONE is the zero value, for unset optional slots.
VAL_TYPES = {
    "none": "RM_MIRROR_VAL_NONE",
    "bool": "RM_MIRROR_VAL_BOOL",
    "u8": "RM_MIRROR_VAL_U8",
    "u16": "RM_MIRROR_VAL_U16",
    "u32": "RM_MIRROR_VAL_U32",
    "i8": "RM_MIRROR_VAL_I8",
    "i16": "RM_MIRROR_VAL_I16",
    "i32": "RM_MIRROR_VAL_I32",
    "i64": "RM_MIRROR_VAL_I64",
    "enum8": "RM_MIRROR_VAL_ENUM8",
    "nullable_u8": "RM_MIRROR_VAL_NULLABLE_U8",
    "nullable_u16": "RM_MIRROR_VAL_NULLABLE_U16",
    "nullable_i64": "RM_MIRROR_VAL_NULLABLE_I64",
    "string": "RM_MIRROR_VAL_STRING",
}

# The subset a write_as command argument may use: TLV-encodable widths only
ARG_TYPES = {k: VAL_TYPES[k] for k in ("u8", "u16", "u32", "i8", "i16", "i32", "bool")}

# The subset a numeric attribute may use (strings go through the port's string ops)
ATTR_TYPES = {k: v for k, v in VAL_TYPES.items() if k not in ("none", "string")}

# Placeholder for the transformed Matter-domain value in a write_as argument
ARG_VALUE_PLACEHOLDER = "$value"

# Command-carrying capability keys: the JSON key, the C prefix the capability table's
# Ref field expects for the command array, and an ident suffix keeping one key's arg
# arrays from colliding with another's on the same capability.
CMD_KEYS = (
    ("write_as", "__write_cmds", ""),
    ("seed_as", "__seed_cmds", "_seed"),
)

# Widths of the generated table fields. Every value narrower than its JSON source is
# range-checked below, so a mapping that does not fit fails the build instead of being
# silently truncated into the tables.
U8_MAX = 0xFF
U32_MAX = 0xFFFFFFFF
I32_MIN = -(1 << 31)
I32_MAX = (1 << 31) - 1

# Composite conversions are enumerated (no scripting in the mapping language);
# the semantics live in the engine (rm_mirror_color.c etc.), keyed by this enum.
COMPOSITE_CONVERSIONS = {
    "hsv_xy": "RM_MIRROR_COMPOSITE_CONV_HSV_XY",
}

# How a StartUp* attribute's stored value becomes the boot state. Enumerated for the
# same reason as composite conversions: the semantics live in the engine.
STARTUP_POLICIES = {
    "passthrough": "RM_MIRROR_STARTUP_PASSTHROUGH",
    "min_clamp": "RM_MIRROR_STARTUP_MIN_CLAMP",
    "toggle_previous": "RM_MIRROR_STARTUP_TOGGLE_PREVIOUS",
}

# The three library sections, and the field naming each entry within them
LIBRARY_SECTIONS = (
    ("capabilities", "capability"),
    ("composites", "id"),
    ("device_types", "device_type"),
)

LIBRARY_KEYS = {"mapping_version", "description"} | {s for s, _ in LIBRARY_SECTIONS}

PROFILE_KEYS = {
    "profile_version",
    "name",
    "description",
    "device_types",
    "capabilities",
    "exclude_capabilities",
}


def _hex(value):
    """Parse a JSON hex-string id (e.g. "0x0300") into an int.

    Matter ids are 32-bit: a manufacturer extension carries the vendor in the upper
    half, so the tables keep the full width rather than assuming standard ids.
    """
    if not isinstance(value, str) or not value.startswith("0x"):
        raise ValueError(f"expected hex string like '0x0300', got {value!r}")
    parsed = int(value, 16)
    if not 0 <= parsed <= U32_MAX:
        raise ValueError(f"id {value} does not fit a 32-bit Matter id")
    return parsed


def _check_count(where, what, count, errors):
    """The tables hold list lengths in a uint8_t."""
    if count > U8_MAX:
        errors.append(f"{where}: {what} has {count} entries, more than {U8_MAX}")


def _check_i32(where, what, value, errors):
    """Values crossing the transform pipeline are int32 end to end (the port reduces
    every Matter numeric to int32), so a mapping constant must fit that."""
    if not isinstance(value, int):
        return
    if not I32_MIN <= value <= I32_MAX:
        errors.append(f"{where}: {what} {value} does not fit an int32")


def _check_u8(where, what, value, errors):
    if isinstance(value, int) and not 0 <= value <= U8_MAX:
        errors.append(f"{where}: {what} {value} does not fit a uint8")


# The C header this generator fills in: hand-written, because the engine reads these
# fields and so owns their shape. Each descriptor below declares the width it assumes,
# and emit_header() turns that into a size assertion against the real field.
TYPES_HEADER = "rm_mirror_mapping.h"


def _quoted(value):
    return "NULL" if value is None else '"%s"' % value


def _boolean(value):
    return "true" if value else "false"


def _hex8(value):
    return "0x%08X" % value


def _hex4(value):
    return "0x%04X" % value


def _hex2(value):
    return "0x%02X" % value


class Scalar:
    """One generated struct field: its C declaration, where it reads from in a JSON
    entry, how it renders, and the width check its C type implies.
    """

    def __init__(self, name, get, render=str, check=None, width=None, note=None):
        self.name = name
        self.get = get
        self.render = render
        self.check = check
        self.width = width
        self.note = note

    def names(self):
        return [self.name]

    def widths_asserted(self):
        return [(self.name, self.width)] if self.width else []

    def arrays(self, entry, ident):
        return []

    def inits(self, entry, ident):
        return [
            (
                self.name,
                self.render(self.get(entry)),
                self.note(entry) if self.note else "",
            )
        ]

    def widths(self, entry, where, errors):
        if self.check:
            self.check(where, self.name, self.get(entry), errors)


class _RawField(Scalar):
    def inits(self, entry, ident):
        return [(self.name, self.get(entry, ident), "")]


class Arr:
    """A list-valued field: the pointer, its uint8_t count, and the static array the
    pointer names, all from one declaration. @p count is None for a list whose length
    another field already carries."""

    def __init__(self, name, elem_type, get, element, prefix, count):
        self.name = name
        self.elem_type = elem_type
        self.get = get
        self.element = element
        self.prefix = prefix
        self.count = count

    def symbol(self, ident):
        return f"{self.prefix}_{ident}"

    def names(self):
        return [self.name] + ([self.count] if self.count else [])

    def widths_asserted(self):
        return [(self.count, 1)] if self.count else []

    def arrays(self, entry, ident):
        items = self.get(entry)
        if not items:
            return []
        rendered = ", ".join(self.element(i) for i in items)
        return [f"static {self.elem_type} {self.symbol(ident)}[] = {{{rendered}}};"]

    def inits(self, entry, ident):
        items = self.get(entry)
        inits = [(self.name, self.symbol(ident) if items else "NULL", "")]
        if self.count:
            inits.append((self.count, str(len(items)), ""))
        return inits

    def widths(self, entry, where, errors):
        _check_count(where, self.name, len(self.get(entry)), errors)


class Ref(Arr):
    """A list-valued field whose array is emitted by hand, because its elements carry
    sub-arrays of their own and so are not a pure function of one item."""

    def arrays(self, entry, ident):
        return []


def Str(name, get):
    return Scalar(name, get, _quoted)


def U32(name, get, render=_hex4, note=None):
    return Scalar(name, get, render, width=4, note=note)


def I32(name, get):
    return Scalar(name, get, check=_check_i32, width=4)


def U8(name, get, note=None):
    return Scalar(name, get, check=_check_u8, width=1, note=note)


def Enum(name, get):
    return Scalar(name, get, width=1)


def Flag(name, get):
    """A 1-bit field: no size assertion, sizeof does not apply to a bitfield."""
    return Scalar(name, get, _boolean)


def Raw(name, get):
    """Escape hatch for a field the descriptors cannot describe (the transform union):
    @p get renders the initialiser itself, and is passed the entry's C identifier."""
    return _RawField(name, get)


class Struct:
    """How to fill one table type declared in rm_mirror_mapping.h."""

    def __init__(self, c_name, fields):
        self.c_name = c_name
        self.fields = fields

    def names(self):
        """Every field this generator fills, as rm_mirror_mapping.h must declare them."""
        return [name for field in self.fields for name in field.names()]

    def assertions(self):
        """One size assertion per field, so a width changed in the hand-written header
        without its descriptor fails the build instead of truncating a value."""
        return [
            f"RM_MIRROR_STATIC_ASSERT(sizeof((({self.c_name} *)0)->{name}) == {width},\n"
            f'                        "{self.c_name}.{name} is not {width} byte(s): '
            f'gen_mapping_table.py assumes it is");'
            for field in self.fields
            for name, width in field.widths_asserted()
        ]

    def arrays(self, entry, ident):
        return [line for f in self.fields for line in f.arrays(entry, ident)]

    def row(self, entry, ident, indent="    "):
        lines = [indent + "{"]
        for field in self.fields:
            for name, value, note in field.inits(entry, ident):
                lines.append(
                    f"{indent}    .{name} = {value},{f' /* {note} */' if note else ''}"
                )
        lines.append(indent + "},")
        return lines

    def inline(self, entry, ident, suffix=""):
        """The entry as a one-line initialiser, for an element of a static array."""
        inits = [i for f in self.fields for i in f.inits(entry, ident)]
        text = "{" + ", ".join(f".{n} = {v}" for n, v, _ in inits) + "}" + suffix
        notes = [n for _, _, n in inits if n]
        return f"{text} /* {notes[0]} */" if notes else text

    def widths(self, entry, where, errors):
        for field in self.fields:
            try:
                field.widths(entry, where, errors)
            except (KeyError, ValueError, TypeError):
                pass  # malformed entry: the structural checks in validate() report it


def _startup(cap):
    return cap.get("startup", {})


def _bounds(cap):
    return cap.get("bounds_from", {})


def _comp_match(comp):
    return comp["matter_match"]


def _feature_map(match):
    """The cluster FeatureMap bits a match asks the port to enable; absent means none."""
    return _hex(match.get("feature_map", "0x00000000"))


# What the generator must fill for each table type declared in rm_mirror_mapping.h:
# per field, where it reads from the JSON, how it renders, the range its width allows,
# and the width itself (asserted against the header). The C type, its comment and the
# field order live in the header - the engine reads these fields, so it owns their shape.
STRUCTS = {}

STRUCTS["cmd_arg"] = Struct(
    "rm_mirror_cmd_arg_t",
    [
        I32(
            "literal",
            lambda a: 0 if a["value"] == ARG_VALUE_PLACEHOLDER else a["value"],
        ),
        U8("field_id", lambda a: a["field"], note=lambda a: a.get("name", "")),
        Enum("type", lambda a: ARG_TYPES[a["type"]]),
        Flag("from_value", lambda a: a["value"] == ARG_VALUE_PLACEHOLDER),
    ],
)

STRUCTS["write_cmd"] = Struct(
    "rm_mirror_write_cmd_t",
    [
        Ref(
            "args",
            "const rm_mirror_cmd_arg_t",
            lambda c: c.get("args", []),
            None,
            "__cmd_args",
            "n_args",
        ),
        U32(
            "command_id",
            lambda c: _hex(c["command"]),
            render=_hex2,
            note=lambda c: c.get("name", ""),
        ),
        I32("when", lambda c: c.get("when", 0)),
        Flag("has_when", lambda c: "when" in c),
    ],
)

STRUCTS["shadow_attr"] = Struct(
    "rm_mirror_shadow_attr_t",
    [
        U32("attribute_id", lambda s: _hex(s["attribute"])),
        Enum("value_type", lambda s: VAL_TYPES[s["value_type"]]),
    ],
)

STRUCTS["capability"] = Struct(
    "rm_mirror_capability_t",
    [
        Str("param_type", lambda c: c["capability"]),
        U32("cluster_id", lambda c: _hex(_attr_match(c)["cluster"])),
        U32("attribute_id", lambda c: _hex(_attr_match(c)["attribute"])),
        Enum("value_type", lambda c: VAL_TYPES[_attr_match(c)["value_type"]]),
        U32("feature_map", lambda c: _feature_map(_attr_match(c)), render=_hex8),
        Raw("xform", lambda c, ident: _xform_init(ident, c["transform"])),
        Ref(
            "write_cmds",
            "const rm_mirror_write_cmd_t",
            lambda c: c.get("write_as", {}).get("commands", []),
            None,
            "__write_cmds",
            "n_write_cmds",
        ),
        Ref(
            "seed_cmds",
            "const rm_mirror_write_cmd_t",
            lambda c: c.get("seed_as", {}).get("commands", []),
            None,
            "__seed_cmds",
            "n_seed_cmds",
        ),
        Arr(
            "shadow_attrs",
            "const rm_mirror_shadow_attr_t",
            lambda c: c.get("shadow_attributes", []),
            lambda s: STRUCTS["shadow_attr"].inline(s, ""),
            "__shadows",
            "n_shadow_attrs",
        ),
        Str("report_as", lambda c: c.get("report_as", {}).get("kind")),
        U32(
            "startup_attr",
            lambda c: _hex(_startup(c)["attribute"]) if _startup(c) else 0,
        ),
        Enum(
            "startup_policy",
            lambda c: (
                STARTUP_POLICIES[_startup(c)["policy"]]
                if _startup(c)
                else "RM_MIRROR_STARTUP_NONE"
            ),
        ),
        I32("startup_min", lambda c: _startup(c).get("min", 0)),
        Flag(
            "startup_skip_on_sw_update",
            lambda c: _startup(c).get("skip_on_software_update", False),
        ),
        Flag("deferred_persistence", lambda c: c.get("deferred_persistence", False)),
        U32(
            "bounds_min_attr",
            lambda c: _bounds_attr(_bounds(c)["min"]) if "min" in _bounds(c) else 0,
        ),
        U32(
            "bounds_max_attr",
            lambda c: _bounds_attr(_bounds(c)["max"]) if "max" in _bounds(c) else 0,
        ),
        Enum(
            "bounds_value_type",
            lambda c: VAL_TYPES[_bounds(c).get("value_type", "none")],
        ),
        Flag("node_scoped", lambda c: _attr_match(c).get("node_scoped", False)),
        Flag("rule_gated", lambda c: c.get("rule_gated", False)),
    ],
)

STRUCTS["composite"] = Struct(
    "rm_mirror_composite_t",
    [
        Str("id", lambda c: c["id"]),
        Arr(
            "param_types",
            "const char *const",
            lambda c: c["params"],
            _quoted,
            "__comp_params",
            "n_params",
        ),
        U32("cluster_id", lambda c: _hex(_comp_match(c)["cluster"])),
        Arr(
            "attribute_ids",
            "const uint32_t",
            lambda c: [_hex(a) for a in _comp_match(c)["attributes"]],
            _hex4,
            "__comp_attrs",
            "n_attributes",
        ),
        Arr(
            "value_types",
            "const rm_mirror_val_type_t",
            lambda c: _comp_match(c)["value_types"],
            lambda t: VAL_TYPES[t],
            "__comp_val_types",
            None,
        ),
        U32("feature_map", lambda c: _feature_map(_comp_match(c)), render=_hex8),
        Enum("conversion", lambda c: COMPOSITE_CONVERSIONS[c["conversion"]["type"]]),
        Flag("deferred_persistence", lambda c: c.get("deferred_persistence", False)),
    ],
)

STRUCTS["extra_devtype"] = Struct(
    "rm_mirror_extra_devtype_t",
    [
        U32("device_type_id", lambda d: _hex(d["id"])),
        U8("device_type_version", lambda d: d["version"]),
        Ref(
            "mandatory_clusters",
            "const uint32_t",
            lambda d: d.get("mandatory_clusters", []),
            None,
            "__rule_extra_clusters",
            "n_mandatory_clusters",
        ),
    ],
)

STRUCTS["devtype_rule"] = Struct(
    "rm_mirror_devtype_rule_t",
    [
        Arr(
            "param_types",
            "const char *const",
            lambda r: r["params"],
            _quoted,
            "__rule_params",
            "n_params",
        ),
        Arr(
            "optional_params",
            "const char *const",
            lambda r: r.get("optional_params", []),
            _quoted,
            "__rule_opt_params",
            "n_optional_params",
        ),
        U32("matter_device_type_id", lambda r: _hex(r["matter_device_type"])),
        U8("matter_device_type_version", lambda r: r["matter_device_type_version"]),
        Arr(
            "mandatory_clusters",
            "const uint32_t",
            lambda r: [_hex(c) for c in r.get("mandatory_clusters", [])],
            _hex4,
            "__rule_clusters",
            "n_mandatory_clusters",
        ),
        Ref(
            "extra_device_types",
            "const rm_mirror_extra_devtype_t",
            lambda r: r.get("additional_device_types", []),
            None,
            "__rule_extra",
            "n_extra_device_types",
        ),
    ],
)

STRUCTS["device_entry"] = Struct(
    "rm_mirror_device_entry_t",
    [
        Str("device_type", lambda e: e["device_type"]),
        Ref(
            "rules",
            "const rm_mirror_devtype_rule_t",
            lambda e: e["rules"],
            None,
            "__rules",
            "n_rules",
        ),
    ],
)


def _attr_match(cap):
    """The Matter location a capability maps to, empty when it declares none."""
    match = cap.get("matter_match")
    return match if isinstance(match, dict) else {}


def _bounds_attr(spec):
    """Parse a bounds_from source like 'attr:0x400B' into an attribute id."""
    if not spec.startswith("attr:"):
        raise ValueError(f"unsupported bounds_from source {spec!r}")
    return _hex(spec[len("attr:") :])


def _validate_commands(name, key, block, errors):
    """Shared shape checks for write_as and seed_as. A seed runs once, with no value to
    substitute and nothing to select on, so it takes neither 'when' nor a placeholder."""
    seeds = key == "seed_as"
    commands = block.get("commands")
    if not isinstance(commands, list) or not commands:
        errors.append(f"{name}: {key} needs a non-empty commands list")
        return
    unconditional = 0
    for i, cmd in enumerate(commands):
        where = f"{name}: {key} command {i}"
        try:
            _hex(cmd["command"])
        except (KeyError, ValueError) as exc:
            errors.append(f"{where}: bad command id: {exc}")
        if "when" in cmd:
            if seeds:
                errors.append(f"{where}: a seed command cannot carry 'when'")
            elif not isinstance(cmd["when"], int):
                errors.append(f"{where}: 'when' must be an integer Matter-domain value")
        else:
            unconditional += 1
        args = cmd.get("args", [])
        if not isinstance(args, list):
            errors.append(f"{where}: args must be a list")
            continue
        fields = set()
        for arg in args:
            if not isinstance(arg.get("field"), int):
                errors.append(f"{where}: arg missing integer field id")
                continue
            if arg["field"] in fields:
                errors.append(f"{where}: duplicate field id {arg['field']}")
            fields.add(arg["field"])
            if arg.get("type") not in ARG_TYPES:
                errors.append(f"{where}: unknown arg type {arg.get('type')!r}")
            value = arg.get("value")
            if seeds:
                if not isinstance(value, int):
                    errors.append(
                        f"{where}: a seed command's args must be integer literals, "
                        f"got {value!r}"
                    )
            elif not isinstance(value, int) and value != ARG_VALUE_PLACEHOLDER:
                errors.append(
                    f"{where}: arg value must be an integer literal or "
                    f"'{ARG_VALUE_PLACEHOLDER}', got {value!r}"
                )
    if not seeds and unconditional > 1:
        errors.append(f"{name}: write_as has more than one unconditional command")


def validate(mapping):
    errors = []
    cap_types = set()
    for cap in mapping.get("capabilities", []):
        name = cap.get("capability", "<missing>")
        for key, _prefix, _suffix in CMD_KEYS:
            if key in cap:
                _validate_commands(name, key, cap[key], errors)
        if name in cap_types:
            errors.append(f"duplicate capability entry: {name}")
        cap_types.add(name)
        matched_attr = None
        match = _attr_match(cap)
        if not match:
            errors.append(f"{name}: matter_match must be a Matter location")
        else:
            try:
                _hex(match["cluster"])
                _feature_map(match)
                matched_attr = _hex(match["attribute"])
            except (KeyError, ValueError) as exc:
                errors.append(f"{name}: bad matter_match: {exc}")
        xform = cap.get("transform", {}).get("type")
        if xform not in XFORM_TYPES:
            errors.append(f"{name}: unknown transform type {xform!r}")
        value_type = _attr_match(cap).get("value_type")
        if value_type not in VAL_TYPES or value_type == "none":
            errors.append(
                f"{name}: matter_match needs a value_type, got {value_type!r}"
            )
        elif (value_type == "string") != (xform == "string"):
            errors.append(
                f"{name}: value_type 'string' and the string transform imply each other"
            )
        bounds = cap.get("bounds_from", {})
        if ("min" in bounds or "max" in bounds) and bounds.get(
            "value_type"
        ) not in ATTR_TYPES:
            errors.append(
                f"{name}: bounds_from needs a value_type, got {bounds.get('value_type')!r}"
            )
        for shadow in cap.get("shadow_attributes", []):
            try:
                attr = _hex(shadow["attribute"])
            except (KeyError, ValueError) as exc:
                errors.append(f"{name}: bad shadow_attributes entry: {exc}")
                continue
            if shadow.get("value_type") not in ATTR_TYPES:
                errors.append(
                    f"{name}: shadow attribute 0x{attr:04X} needs a value_type, "
                    f"got {shadow.get('value_type')!r}"
                )
            if attr == matched_attr:
                errors.append(f"{name}: shadow attribute repeats the matched attribute")
        if "startup" in cap:
            startup = cap["startup"]
            try:
                _hex(startup["attribute"])
            except (KeyError, ValueError) as exc:
                errors.append(f"{name}: bad startup attribute: {exc}")
            policy = startup.get("policy")
            if policy not in STARTUP_POLICIES:
                errors.append(f"{name}: unknown startup policy {policy!r}")
            if policy == "min_clamp" and not isinstance(startup.get("min"), int):
                errors.append(f"{name}: min_clamp startup policy missing integer min")
        if not isinstance(cap.get("deferred_persistence", False), bool):
            errors.append(f"{name}: deferred_persistence must be a boolean")
        if "report_as" in cap:
            kind = cap["report_as"].get("kind")
            if not isinstance(kind, str) or not kind:
                errors.append(f"{name}: report_as needs a non-empty kind")
            if "write_as" in cap:
                errors.append(
                    f"{name}: report_as is for values Matter does not expose as a "
                    f"writable attribute, so it cannot carry write_as commands"
                )
        if xform == "string":
            if not isinstance(cap["transform"].get("max_len"), int):
                errors.append(f"{name}: string transform missing integer max_len")
            _check_i32(name, "string max_len", cap["transform"].get("max_len"), errors)
        if xform == "scale":
            factor = cap["transform"].get("factor")
            if not isinstance(factor, int) or factor == 0:
                errors.append(
                    f"{name}: scale transform needs a non-zero integer factor"
                )
            _check_i32(name, "scale factor", factor, errors)
        if xform == "linear":
            for key in ("in_min", "in_max", "out_min", "out_max"):
                if not isinstance(cap["transform"].get(key), int):
                    errors.append(f"{name}: linear transform missing integer {key}")
                _check_i32(name, f"linear {key}", cap["transform"].get(key), errors)
        if xform == "enum_map":
            pairs = cap["transform"].get("map", [])
            aliases = cap["transform"].get("matter_aliases", [])
            if not pairs:
                errors.append(f"{name}: enum_map transform with empty map")
            _check_count(name, "enum_map map", len(pairs), errors)
            _check_count(name, "enum_map matter_aliases", len(aliases), errors)
            seen_rmng, seen_matter = set(), set()
            for pair in pairs + aliases:
                if not isinstance(pair.get("rmng"), int) or not isinstance(
                    pair.get("matter"), int
                ):
                    errors.append(f"{name}: enum_map pair members must be integers")
                _check_i32(name, "enum_map rmng value", pair.get("rmng"), errors)
                _check_i32(name, "enum_map matter value", pair.get("matter"), errors)
            for pair in pairs:
                if pair.get("rmng") in seen_rmng:
                    errors.append(f"{name}: duplicate rmng key in enum_map")
                if pair.get("matter") in seen_matter:
                    errors.append(f"{name}: duplicate matter key in enum_map")
                seen_rmng.add(pair.get("rmng"))
                seen_matter.add(pair.get("matter"))

    for comp in mapping.get("composites", []):
        cid = comp.get("id", "<missing>")
        conv = comp.get("conversion", {}).get("type")
        if conv not in COMPOSITE_CONVERSIONS:
            errors.append(f"composite {cid}: unknown conversion type {conv!r}")
        if not isinstance(comp.get("deferred_persistence", False), bool):
            errors.append(f"composite {cid}: deferred_persistence must be a boolean")
        params = comp.get("params", [])
        attrs = comp.get("matter_match", {}).get("attributes", [])
        value_types = comp.get("matter_match", {}).get("value_types", [])
        if len(value_types) != len(attrs) or any(
            v not in ATTR_TYPES for v in value_types
        ):
            errors.append(
                f"composite {cid}: matter_match needs one value_type per attribute"
            )
        unknown = set(params) - cap_types
        if unknown:
            errors.append(
                f"composite {cid}: params not in capabilities: {sorted(unknown)}"
            )
        if conv == "hsv_xy" and (len(params) != 2 or len(attrs) != 2):
            errors.append(
                f"composite {cid}: hsv_xy requires exactly 2 params (hue, saturation) "
                f"and 2 attributes (CurrentX, CurrentY)"
            )
        try:
            _hex(comp["matter_match"]["cluster"])
            for attr in attrs:
                _hex(attr)
            _feature_map(comp["matter_match"])
        except (KeyError, ValueError) as exc:
            errors.append(f"composite {cid}: bad matter_match: {exc}")

    for entry in mapping.get("device_types", []):
        dev = entry.get("device_type", "<missing>")
        rules = entry.get("rules", [])
        if not rules:
            errors.append(f"{dev}: no rules")
        for i, rule in enumerate(rules):
            params = set(rule.get("params", []))
            if not params:
                errors.append(f"{dev} rule {i}: empty params")
            unknown = (params | set(rule.get("optional_params", []))) - cap_types
            if unknown:
                errors.append(
                    f"{dev} rule {i}: params not in capabilities: {sorted(unknown)}"
                )
            try:
                _hex(rule["matter_device_type"])
            except (KeyError, ValueError) as exc:
                errors.append(f"{dev} rule {i}: bad matter_device_type: {exc}")
            for dt in rule.get("additional_device_types", []):
                try:
                    _hex(dt["id"])
                    for cluster in dt.get("mandatory_clusters", []):
                        _hex(cluster)
                except (KeyError, ValueError) as exc:
                    errors.append(
                        f"{dev} rule {i}: bad additional_device_types entry: {exc}"
                    )
                if not isinstance(dt.get("version"), int):
                    errors.append(
                        f"{dev} rule {i}: additional_device_types entry needs an integer version"
                    )
            # Most-specific-first: a later rule must not shadow-proof an earlier one
            for j in range(i):
                earlier = set(rules[j].get("params", []))
                if earlier <= params:
                    errors.append(
                        f"{dev} rule {i} is unreachable: its param set is a superset "
                        f"of earlier rule {j} (order rules most-specific-first)"
                    )
    _check_widths(mapping, errors)
    return errors


def _check_widths(mapping, errors):
    """The range checks the generated field widths imply, driven by the same
    descriptors that emit them - so a narrowed field cannot silently truncate."""
    for cap in mapping.get("capabilities", []):
        where = cap.get("capability", "<missing>")
        STRUCTS["capability"].widths(cap, where, errors)
        for shadow in cap.get("shadow_attributes", []):
            STRUCTS["shadow_attr"].widths(shadow, where, errors)
        for key, _prefix, _suffix in CMD_KEYS:
            for i, cmd in enumerate(cap.get(key, {}).get("commands", [])):
                cmd_where = f"{where}: {key} command {i}"
                STRUCTS["write_cmd"].widths(cmd, cmd_where, errors)
                for arg in cmd.get("args", []):
                    STRUCTS["cmd_arg"].widths(arg, cmd_where, errors)
    for comp in mapping.get("composites", []):
        STRUCTS["composite"].widths(
            comp, f"composite {comp.get('id', '<missing>')}", errors
        )
    for entry in mapping.get("device_types", []):
        dev = entry.get("device_type", "<missing>")
        STRUCTS["device_entry"].widths(entry, dev, errors)
        for i, rule in enumerate(entry.get("rules", [])):
            rule_where = f"{dev} rule {i}"
            STRUCTS["devtype_rule"].widths(rule, rule_where, errors)
            for dt in rule.get("additional_device_types", []):
                STRUCTS["extra_devtype"].widths(dt, rule_where, errors)


def load_library(paths):
    """Merge the library files into one mapping, in the order given.

    Entries are keyed by capability / composite id / device type; a key defined
    twice is an error rather than a silent last-one-wins, so a product's own
    library file cannot quietly redefine the shared vocabulary.
    """
    merged = {section: [] for section, _ in LIBRARY_SECTIONS}
    seen = {section: {} for section, _ in LIBRARY_SECTIONS}
    version = None
    errors = []
    for path in paths:
        with open(path, encoding="utf-8") as f:
            doc = json.load(f)
        where = path.rsplit("/", 1)[-1]
        unknown = set(doc) - LIBRARY_KEYS
        if unknown:
            errors.append(f"{where}: unknown library keys {sorted(unknown)}")
        if "mapping_version" in doc:
            if version is not None and doc["mapping_version"] != version:
                errors.append(
                    f"{where}: mapping_version {doc['mapping_version']!r} disagrees "
                    f"with {version!r} from an earlier library file"
                )
            version = doc["mapping_version"]
        for section, id_key in LIBRARY_SECTIONS:
            for entry in doc.get(section, []):
                key = entry.get(id_key)
                if key in seen[section]:
                    errors.append(
                        f"{where}: {section} entry {key!r} already defined in "
                        f"{seen[section][key]}"
                    )
                    continue
                seen[section][key] = where
                merged[section].append(entry)
    if version is None:
        errors.append("no library file declares a mapping_version")
    merged["mapping_version"] = version
    return merged, errors


def _rule_without(rule, excluded):
    """Copy @p rule with the excluded capabilities dropped from optional_params."""
    optional = [p for p in rule.get("optional_params", []) if p not in excluded]
    out = dict(rule)
    if optional:
        out["optional_params"] = optional
    else:
        out.pop("optional_params", None)
    return out


def resolve(library, profile):
    """Restrict the library to what @p profile selects.

    Keeps a capability when it is (a) node-scoped, (b) referenced by a kept
    rule's params/optional_params, (c) targeting a cluster listed as mandatory
    by a kept rule (e.g. identify), or (d) named by the profile outright. A
    composite is kept when all its member params are. Everything else is
    dropped, which is what makes unused library entries cost no flash.
    """
    errors = []
    unknown = set(profile) - PROFILE_KEYS
    if unknown:
        errors.append(f"unknown profile keys {sorted(unknown)}")

    known_devices = {e.get("device_type") for e in library["device_types"]}
    wanted = profile.get("device_types", "*")
    if wanted == "*":
        kept_devices = list(library["device_types"])
    elif isinstance(wanted, list):
        missing = [d for d in wanted if d not in known_devices]
        if missing:
            errors.append(f"device types not in the library: {sorted(missing)}")
        kept_devices = [
            e for e in library["device_types"] if e.get("device_type") in set(wanted)
        ]
    else:
        errors.append('device_types must be a list or "*"')
        kept_devices = []

    required = set()
    referenced = set()
    mandatory_clusters = set()
    for entry in kept_devices:
        for rule in entry.get("rules", []):
            required.update(rule.get("params", []))
            referenced.update(rule.get("params", []))
            referenced.update(rule.get("optional_params", []))
            mandatory_clusters.update(
                _hex(c) for c in rule.get("mandatory_clusters", [])
            )
            for dt in rule.get("additional_device_types", []):
                mandatory_clusters.update(
                    _hex(c) for c in dt.get("mandatory_clusters", [])
                )

    known_caps = {c.get("capability") for c in library["capabilities"]}
    extra = profile.get("capabilities", [])
    excluded = set(profile.get("exclude_capabilities", []))
    for name in sorted(set(extra) | excluded):
        if name not in known_caps:
            errors.append(f"capability not in the library: {name}")
    # A rule cannot match without its required params, so excluding one would
    # leave the device type unmatchable. Optional params are fair game.
    for name in sorted(excluded & required):
        errors.append(
            f"{name} is required by a kept device rule and cannot be excluded"
        )
    referenced.update(extra)

    kept_caps = [
        c
        for c in library["capabilities"]
        if (
            _attr_match(c).get("node_scoped", False)
            or c.get("capability") in referenced
            or _hex(_attr_match(c)["cluster"]) in mandatory_clusters
        )
        and c.get("capability") not in excluded
    ]
    kept_names = {c.get("capability") for c in kept_caps}
    kept_composites = [
        c for c in library["composites"] if set(c.get("params", [])) <= kept_names
    ]
    # A rule must not gate-list a capability that is no longer compiled in, so
    # drop excluded names from optional_params (required ones errored above).
    if excluded:
        kept_devices = [
            dict(entry, rules=[_rule_without(r, excluded) for r in entry["rules"]])
            for entry in kept_devices
        ]

    dropped = (
        len(library["capabilities"])
        - len(kept_caps)
        + len(library["composites"])
        - len(kept_composites)
        + len(library["device_types"])
        - len(kept_devices)
    )
    if dropped and not errors:
        print(
            f"gen_mapping_table: profile {profile.get('name', '?')!r} keeps "
            f"{len(kept_devices)} device type(s), {len(kept_caps)} capability(ies), "
            f"{len(kept_composites)} composite(s); {dropped} library entry(ies) dropped",
            file=sys.stderr,
        )

    return {
        "mapping_version": library["mapping_version"],
        "capabilities": kept_caps,
        "composites": kept_composites,
        "device_types": kept_devices,
    }, errors


def _any_seed_cmds(mapping):
    return any(
        cap.get("seed_as", {}).get("commands")
        for cap in mapping.get("capabilities", [])
    )


def emit_header(mapping, source_name):
    """The per-mapping half of the header: what this mapping needs compiled in, and the
    assertions tying the descriptors to the hand-written types."""
    lines = [GENERATED_BANNER.format(source=source_name)]
    lines.append("#ifndef __RM_MIRROR_MAPPING_GEN_H__")
    lines.append("#define __RM_MIRROR_MAPPING_GEN_H__")
    lines.append("")
    lines.append(f'#include "{TYPES_HEADER}"')
    lines.append("")
    lines.append(
        "/* Clusters this mapping needs the port to build. The port compiles in only the"
    )
    lines.append(" * matching factories (src/port/clusters/). */")
    for cid in port_clusters(mapping):
        lines.append(f"#define RM_MIRROR_USES_CLUSTER_{cid:04X} 1")
    lines.append("")
    lines.append(
        "/* Whether any capability declares a seed_as command, i.e. whether the engine has a"
    )
    lines.append(
        " * server holding its own copy of an attribute to seed after the reseed. */"
    )
    lines.append(
        f"#define RM_MIRROR_SEEDS_SHADOWS {1 if _any_seed_cmds(mapping) else 0}"
    )
    lines.append("")
    lines.append(
        "/* Engine vocabulary this mapping exercises: transforms, composite conversions"
    )
    lines.append(" * and startup policies. The engine compiles in only these. */")
    for macro in vocabulary_macros(mapping):
        lines.append(f"#define {macro} 1")
    lines.append("")
    lines.append(
        f"/* The table fields this generator fills, against the widths {TYPES_HEADER}"
    )
    lines.append(" * declares. A width changed there alone stops the build here. */")
    for struct in STRUCTS.values():
        lines += struct.assertions()
    lines.append("")
    lines.append("#endif /* __RM_MIRROR_MAPPING_GEN_H__ */")
    return "\n".join(lines) + "\n"


def port_clusters(mapping):
    """Clusters the port's factory must build for @p mapping, each with the union
    of the FeatureMap bits the mapping asks for.

    Node-scoped matches are left out: they bind on endpoint 0, whose clusters the
    Matter stack provides rather than the mirror's factory.
    """
    clusters = {}
    for cap in mapping["capabilities"]:
        match = _attr_match(cap)
        if match.get("node_scoped", False):
            continue
        cid = _hex(match["cluster"])
        clusters[cid] = clusters.get(cid, 0) | _feature_map(match)
    for comp in mapping["composites"]:
        cid = _hex(comp["matter_match"]["cluster"])
        clusters[cid] = clusters.get(cid, 0) | _feature_map(comp["matter_match"])
    for entry in mapping["device_types"]:
        for rule in entry.get("rules", []):
            for cluster in rule.get("mandatory_clusters", []):
                clusters.setdefault(_hex(cluster), 0)
            for dt in rule.get("additional_device_types", []):
                for cluster in dt.get("mandatory_clusters", []):
                    clusters.setdefault(_hex(cluster), 0)
    return dict(sorted(clusters.items()))


def vocabulary_macros(mapping):
    """The engine vocabulary this mapping exercises, as macro names.

    The engine gates its per-transform / per-conversion / per-startup-policy
    code on these, so a profile that never asks for (say) the hue/saturation to
    XY conversion does not carry the colour maths.
    """
    macros = []
    xforms = {c["transform"]["type"] for c in mapping["capabilities"]}
    for name in sorted(xforms):
        macros.append(
            f"RM_MIRROR_USES_XFORM_{XFORM_TYPES[name][len('RM_MIRROR_XFORM_') :]}"
        )
    if mapping["composites"]:
        macros.append("RM_MIRROR_USES_COMPOSITES")
    for conv in sorted({c["conversion"]["type"] for c in mapping["composites"]}):
        macros.append(
            f"RM_MIRROR_USES_CONV_{COMPOSITE_CONVERSIONS[conv][len('RM_MIRROR_COMPOSITE_CONV_') :]}"
        )
    policies = {
        c["startup"]["policy"] for c in mapping["capabilities"] if "startup" in c
    }
    for policy in sorted(policies):
        macros.append(
            f"RM_MIRROR_USES_STARTUP_{STARTUP_POLICIES[policy][len('RM_MIRROR_STARTUP_') :]}"
        )
    return macros


def emit_cluster_check(mapping, source_name, allow_external):
    """Emit the port cross-check: every cluster the mapping needs must have a
    factory in the port, or the build fails naming the cluster.

    Included by the port after its per-cluster factories have defined their
    RM_MIRROR_PORT_HAS_CLUSTER_* markers, so this cannot live in the mapping
    header. With @p allow_external the product promises a runtime factory
    (esp_rmaker_matter_mirror_register_cluster_factory), so the check is
    reduced to a record of what is expected.
    """
    lines = [GENERATED_BANNER.format(source=source_name)]
    lines.append("#ifndef __RM_MIRROR_CLUSTER_CHECK_GEN_H__")
    lines.append("#define __RM_MIRROR_CLUSTER_CHECK_GEN_H__")
    lines.append("")
    if allow_external:
        lines.append(
            "/* Cluster factories may be registered at runtime, so a missing one is not a build error. */"
        )
    for cid in port_clusters(mapping):
        if allow_external:
            lines.append(f"/* cluster 0x{cid:04X} */")
            continue
        lines.append(f"#if !defined(RM_MIRROR_PORT_HAS_CLUSTER_{cid:04X})")
        lines.append(
            f'#error "Matter mirror: the mapping needs cluster 0x{cid:04X}, which the port cannot build. '
            f"Add a factory under src/port/clusters/, or register one at runtime and enable "
            f'CONFIG_ESP_RMAKER_NEO_MATTER_MIRROR_EXTERNAL_CLUSTERS."'
        )
        lines.append("#endif")
    lines.append("")
    lines.append("#endif /* __RM_MIRROR_CLUSTER_CHECK_GEN_H__ */")
    return "\n".join(lines) + "\n"


def _c_ident(text):
    return text.replace(".", "_").replace("-", "_")


def _xform_init(ident, xform):
    """The rm_mirror_xform_t initialiser for @p xform: type, plus the one union arm
    the type names. Identity and kelvin/mireds carry no payload."""
    kind = xform["type"]
    parts = [f".type = {XFORM_TYPES[kind]}"]
    if kind == "linear":
        parts.append(
            ".u.linear = {%d, %d, %d, %d}"
            % (xform["in_min"], xform["in_max"], xform["out_min"], xform["out_max"])
        )
    elif kind == "string":
        parts.append(f".u.scalar = {xform['max_len']}")
    elif kind == "scale":
        parts.append(f".u.scalar = {xform['factor']}")
    elif kind == "enum_map":
        aliases = xform.get("matter_aliases", [])
        aliases_ref = f"__aliases_{ident}" if aliases else "NULL"
        parts.append(f".n_pairs = {len(xform['map'])}")
        parts.append(f".n_aliases = {len(aliases)}")
        parts.append(f".u.enum_map = {{__pairs_{ident}, {aliases_ref}}}")
    return "{" + ", ".join(parts) + "}"


def _xform_arrays(cap, ident):
    """The enum_map pair arrays the transform union points at."""
    xform = cap["transform"]
    if xform["type"] != "enum_map":
        return []

    def pairs(items):
        return ", ".join(f"{{{p['rmng']}, {p['matter']}}}" for p in items)

    lines = [
        f"static const rm_mirror_enum_pair_t __pairs_{ident}[] = {{{pairs(xform['map'])}}};"
    ]
    aliases = xform.get("matter_aliases", [])
    if aliases:
        lines.append(
            f"static const rm_mirror_enum_pair_t __aliases_{ident}[] = {{{pairs(aliases)}}};"
        )
    return lines


def _cmd_arrays(cap, ident):
    """A capability's command payloads: one arg array per command, then the command
    array itself. Hand-emitted because each command carries an array of its own."""
    lines = []
    for key, cmds_prefix, suffix in CMD_KEYS:
        commands = cap.get(key, {}).get("commands", [])
        if not commands:
            continue
        for i, cmd in enumerate(commands):
            args = cmd.get("args", [])
            if not args:
                continue
            lines.append(
                f"static const rm_mirror_cmd_arg_t __cmd_args_{ident}{suffix}_{i}[] = {{"
            )
            lines += [f"    {STRUCTS['cmd_arg'].inline(arg, '', ',')}" for arg in args]
            lines.append("};")
        lines.append(f"static const rm_mirror_write_cmd_t {cmds_prefix}_{ident}[] = {{")
        for i, cmd in enumerate(commands):
            lines += STRUCTS["write_cmd"].row(cmd, f"{ident}{suffix}_{i}")
        lines.append("};")
    return lines


def _rule_arrays(entry, dev_ident):
    """A device type's rule arrays, and the extra-device-type arrays they point at."""
    lines = []
    for i, rule in enumerate(entry["rules"]):
        rid = f"{dev_ident}_{i}"
        lines += STRUCTS["devtype_rule"].arrays(rule, rid)
        extra = rule.get("additional_device_types", [])
        for j, dt in enumerate(extra):
            clusters = dt.get("mandatory_clusters", [])
            if clusters:
                vals = ", ".join(_hex4(_hex(c)) for c in clusters)
                lines.append(
                    f"static const uint32_t __rule_extra_clusters_{rid}_{j}[] = {{{vals}}};"
                )
        if extra:
            lines.append(
                f"static const rm_mirror_extra_devtype_t __rule_extra_{rid}[] = {{"
            )
            lines += [
                f"    {STRUCTS['extra_devtype'].inline(dt, f'{rid}_{j}', ',')}"
                for j, dt in enumerate(extra)
            ]
            lines.append("};")
    lines.append(f"static const rm_mirror_devtype_rule_t __rules_{dev_ident}[] = {{")
    for i, rule in enumerate(entry["rules"]):
        lines += STRUCTS["devtype_rule"].row(rule, f"{dev_ident}_{i}")
    lines.append("};")
    return lines


def _table(c_name, symbol, desc, entries, ident_of):
    """A top-level table and its count."""
    lines = [f"const {c_name} {symbol}[] = {{"]
    for entry in entries:
        lines += desc.row(entry, ident_of(entry))
    lines.append("};")
    lines.append(
        f"const size_t {symbol.replace('rm_mirror_', 'rm_mirror_n_', 1)} = "
        f"sizeof({symbol}) / sizeof({symbol}[0]);"
    )
    return lines


def emit_source(mapping, source_name, header_name):
    lines = [GENERATED_BANNER.format(source=source_name)]
    lines.append(f'#include "{header_name}"')
    lines.append("")
    lines.append(
        f'const char *const rm_mirror_mapping_version = "{mapping["mapping_version"]}";'
    )
    lines.append("")

    for cap in mapping["capabilities"]:
        ident = _c_ident(cap["capability"])
        lines += _xform_arrays(cap, ident)
        lines += STRUCTS["capability"].arrays(cap, ident)
        lines += _cmd_arrays(cap, ident)
    lines.append("")
    lines += _table(
        "rm_mirror_capability_t",
        "rm_mirror_capabilities",
        STRUCTS["capability"],
        mapping["capabilities"],
        lambda c: _c_ident(c["capability"]),
    )
    lines.append("")

    composites = mapping.get("composites", [])
    for comp in composites:
        lines += STRUCTS["composite"].arrays(comp, _c_ident(comp["id"]))
    if composites:
        lines.append("")
        lines += _table(
            "rm_mirror_composite_t",
            "rm_mirror_composites",
            STRUCTS["composite"],
            composites,
            lambda c: _c_ident(c["id"]),
        )
    else:
        # ISO C forbids empty arrays/initializers; emit one zeroed entry, count 0.
        lines.append("const rm_mirror_composite_t rm_mirror_composites[1] = {{0}};")
        lines.append("const size_t rm_mirror_n_composites = 0;")
    lines.append("")

    for entry in mapping["device_types"]:
        lines += _rule_arrays(entry, _c_ident(entry["device_type"]))
    lines.append("")
    lines += _table(
        "rm_mirror_device_entry_t",
        "rm_mirror_device_entries",
        STRUCTS["device_entry"],
        mapping["device_types"],
        lambda e: _c_ident(e["device_type"]),
    )
    return "\n".join(lines) + "\n"


def _report(errors):
    for err in errors:
        print(f"gen_mapping_table: {err}", file=sys.stderr)
    return 1


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--lib",
        required=True,
        action="append",
        metavar="PATH",
        help="library JSON file: capabilities, composites and device-type rules (repeatable)",
    )
    parser.add_argument(
        "--profile",
        required=True,
        metavar="PATH",
        help="profile JSON file naming the device types to compile in",
    )
    parser.add_argument("--output-c", required=True, help="generated C source path")
    parser.add_argument("--output-h", required=True, help="generated C header path")
    parser.add_argument(
        "--output-check",
        required=True,
        help="generated port cross-check header path",
    )
    parser.add_argument(
        "--allow-external-clusters",
        action="store_true",
        help="a cluster with no compiled-in factory is not a build error: the "
        "application registers one at runtime",
    )
    args = parser.parse_args(argv)

    library, errors = load_library(args.lib)
    if errors:
        return _report(errors)

    # Validate the whole library, so rot in an entry no profile selects still
    # fails the build rather than waiting for the product that needs it.
    errors = validate(library)
    if errors:
        return _report(errors)

    with open(args.profile, encoding="utf-8") as f:
        profile = json.load(f)

    mapping, errors = resolve(library, profile)
    if errors:
        where = args.profile.rsplit("/", 1)[-1]
        return _report(f"{where}: {err}" for err in errors)

    errors = validate(mapping)
    if errors:
        return _report(errors)

    source_name = ", ".join(p.rsplit("/", 1)[-1] for p in args.lib)
    source_name += f" (profile: {profile.get('name', '?')})"
    header_name = TYPES_HEADER
    with open(args.output_h, "w", encoding="utf-8") as f:
        f.write(emit_header(mapping, source_name))
    with open(args.output_c, "w", encoding="utf-8") as f:
        f.write(emit_source(mapping, source_name, header_name))
    with open(args.output_check, "w", encoding="utf-8") as f:
        f.write(emit_cluster_check(mapping, source_name, args.allow_external_clusters))
    return 0


if __name__ == "__main__":
    sys.exit(main())
