#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
#
# SPDX-License-Identifier: Apache-2.0

"""Generate the C mapping tables for the RainMaker Neo Matter mirror.

The mapping vocabulary and its validator are shared with every other consumer and live in
scripts/mapping/ (a copy of esp-rainmaker-neo-matter-mapping; see mapping/SOURCE). This
script owns only the lowering into C: the table layout, the cluster cross-check the port
compiles, and the RM_MIRROR_USES_* gates.

A profile (mapping/profiles/*.json) names the device types a product ships, and the tables
carry that selection alone - capabilities and composites nothing kept references are
dropped, so unused vocabulary costs no flash.
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from mapping import vocabulary  # noqa: E402
from mapping.validate import (  # noqa: E402
    attr_match,
    bounds_attr,
    feature_map,
    load_library,
    report,
    resolve,
    validate,
)
from mapping.vocabulary import (  # noqa: E402
    ARG_VALUE_PLACEHOLDER,
    check_i32,
    parse_hex,
)

PROG = "gen_mapping_table"

# Widths of the generated table fields. A list length and a narrowed scalar are this port's
# constraints, not the mapping language's, so the checks live with the descriptors that emit them.
U8_MAX = 0xFF


def check_count(where, what, count, errors):
    """The tables hold list lengths in a uint8_t."""
    if count > U8_MAX:
        errors.append(f"{where}: {what} has {count} entries, more than {U8_MAX}")


def check_u8(where, what, value, errors):
    if isinstance(value, int) and not 0 <= value <= U8_MAX:
        errors.append(f"{where}: {what} {value} does not fit a uint8")


GENERATED_BANNER = """/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/* Auto-generated by gen_mapping_table.py from {source} - DO NOT EDIT */
"""

# The mapping vocabulary lowered to this port's C enum symbols. The keys must cover what
# the shared vocabulary declares - see _check_vocabulary below.
XFORM_TYPES = {
    "identity": "RM_MIRROR_XFORM_IDENTITY",
    "linear": "RM_MIRROR_XFORM_LINEAR",
    "kelvin_mireds": "RM_MIRROR_XFORM_KELVIN_MIREDS",
    "enum_map": "RM_MIRROR_XFORM_ENUM_MAP",
    "string": "RM_MIRROR_XFORM_STRING",
    "scale": "RM_MIRROR_XFORM_SCALE",
}

VAL_TYPES = {
    "none": "RM_MIRROR_VAL_NONE",
    "bool": "RM_MIRROR_VAL_BOOL",
    "u8": "RM_MIRROR_VAL_U8",
    "u16": "RM_MIRROR_VAL_U16",
    "u32": "RM_MIRROR_VAL_U32",
    "i8": "RM_MIRROR_VAL_I8",
    "i16": "RM_MIRROR_VAL_I16",
    "i32": "RM_MIRROR_VAL_I32",
    "i64": "RM_MIRROR_VAL_I64",
    "enum8": "RM_MIRROR_VAL_ENUM8",
    "nullable_u8": "RM_MIRROR_VAL_NULLABLE_U8",
    "nullable_u16": "RM_MIRROR_VAL_NULLABLE_U16",
    "nullable_i64": "RM_MIRROR_VAL_NULLABLE_I64",
    "string": "RM_MIRROR_VAL_STRING",
}

ARG_TYPES = {k: VAL_TYPES[k] for k in vocabulary.ARG_TYPES}

ATTR_TYPES = {k: VAL_TYPES[k] for k in vocabulary.ATTR_TYPES}

COMPOSITE_CONVERSIONS = {
    "hsv_xy": "RM_MIRROR_COMPOSITE_CONV_HSV_XY",
}

STARTUP_POLICIES = {
    "passthrough": "RM_MIRROR_STARTUP_PASSTHROUGH",
    "min_clamp": "RM_MIRROR_STARTUP_MIN_CLAMP",
    "toggle_previous": "RM_MIRROR_STARTUP_TOGGLE_PREVIOUS",
}

# Command-carrying capability keys: the JSON key, the C prefix the capability table's Ref
# field expects for the command array, and an ident suffix keeping one key's arg arrays
# from colliding with another's on the same capability.
CMD_KEYS = (
    ("write_as", "__write_cmds", ""),
    ("seed_as", "__seed_cmds", "_seed"),
)


def _check_vocabulary():
    """Fail the sync, not the build, when the mapping declares a primitive this port has no
    C symbol for."""
    for what, ours, theirs in (
        ("transform kinds", XFORM_TYPES, vocabulary.XFORM_TYPES),
        ("value types", VAL_TYPES, vocabulary.VAL_TYPES),
        (
            "composite conversions",
            COMPOSITE_CONVERSIONS,
            vocabulary.COMPOSITE_CONVERSIONS,
        ),
        ("startup policies", STARTUP_POLICIES, vocabulary.STARTUP_POLICIES),
        ("command keys", {k for k, _p, _s in CMD_KEYS}, set(vocabulary.CMD_KEYS)),
    ):
        missing = set(theirs) - set(ours)
        if missing:
            raise SystemExit(
                f"{PROG}: the mapping declares {what} {sorted(missing)}, which this port "
                f"does not implement; add them to the engine and to this table"
            )


_check_vocabulary()

# The C header this generator fills in: hand-written, because the engine reads these
# fields and so owns their shape. Each descriptor below declares the width it assumes,
# and emit_header() turns that into a size assertion against the real field.
TYPES_HEADER = "rm_mirror_mapping.h"

# Values a golden-vector row holds per side. The test static-asserts this covers
# RM_MIRROR_COMPOSITE_MAX_PARAMS and _MAX_ATTRS, which the types header declares.
VEC_MAX_VALS = 4


def _quoted(value):
    return "NULL" if value is None else '"%s"' % value


def _boolean(value):
    return "true" if value else "false"


def _hex8(value):
    return "0x%08X" % value


def _hex4(value):
    return "0x%04X" % value


def _hex2(value):
    return "0x%02X" % value


class Scalar:
    """One generated struct field: its C declaration, where it reads from in a JSON
    entry, how it renders, and the width check its C type implies.
    """

    def __init__(self, name, get, render=str, check=None, width=None, note=None):
        self.name = name
        self.get = get
        self.render = render
        self.check = check
        self.width = width
        self.note = note

    def names(self):
        return [self.name]

    def widths_asserted(self):
        return [(self.name, self.width)] if self.width else []

    def arrays(self, entry, ident):
        return []

    def inits(self, entry, ident):
        return [
            (
                self.name,
                self.render(self.get(entry)),
                self.note(entry) if self.note else "",
            )
        ]

    def widths(self, entry, where, errors):
        if self.check:
            self.check(where, self.name, self.get(entry), errors)


class _RawField(Scalar):
    def inits(self, entry, ident):
        return [(self.name, self.get(entry, ident), "")]


class Arr:
    """A list-valued field: the pointer, its uint8_t count, and the static array the
    pointer names, all from one declaration. @p count is None for a list whose length
    another field already carries."""

    def __init__(self, name, elem_type, get, element, prefix, count):
        self.name = name
        self.elem_type = elem_type
        self.get = get
        self.element = element
        self.prefix = prefix
        self.count = count

    def symbol(self, ident):
        return f"{self.prefix}_{ident}"

    def names(self):
        return [self.name] + ([self.count] if self.count else [])

    def widths_asserted(self):
        return [(self.count, 1)] if self.count else []

    def arrays(self, entry, ident):
        items = self.get(entry)
        if not items:
            return []
        rendered = ", ".join(self.element(i) for i in items)
        return [f"static {self.elem_type} {self.symbol(ident)}[] = {{{rendered}}};"]

    def inits(self, entry, ident):
        items = self.get(entry)
        inits = [(self.name, self.symbol(ident) if items else "NULL", "")]
        if self.count:
            inits.append((self.count, str(len(items)), ""))
        return inits

    def widths(self, entry, where, errors):
        check_count(where, self.name, len(self.get(entry)), errors)


class Ref(Arr):
    """A list-valued field whose array is emitted by hand, because its elements carry
    sub-arrays of their own and so are not a pure function of one item."""

    def arrays(self, entry, ident):
        return []


def Str(name, get):
    return Scalar(name, get, _quoted)


def U32(name, get, render=_hex4, note=None):
    return Scalar(name, get, render, width=4, note=note)


def I32(name, get):
    return Scalar(name, get, check=check_i32, width=4)


def U8(name, get, note=None):
    return Scalar(name, get, check=check_u8, width=1, note=note)


def Enum(name, get):
    return Scalar(name, get, width=1)


def Flag(name, get):
    """A 1-bit field: no size assertion, sizeof does not apply to a bitfield."""
    return Scalar(name, get, _boolean)


def Raw(name, get):
    """Escape hatch for a field the descriptors cannot describe (the transform union):
    @p get renders the initialiser itself, and is passed the entry's C identifier."""
    return _RawField(name, get)


class Struct:
    """How to fill one table type declared in rm_mirror_mapping.h."""

    def __init__(self, c_name, fields):
        self.c_name = c_name
        self.fields = fields

    def names(self):
        """Every field this generator fills, as rm_mirror_mapping.h must declare them."""
        return [name for field in self.fields for name in field.names()]

    def assertions(self):
        """One size assertion per field, so a width changed in the hand-written header
        without its descriptor fails the build instead of truncating a value."""
        return [
            f"RM_MIRROR_STATIC_ASSERT(sizeof((({self.c_name} *)0)->{name}) == {width},\n"
            f'                        "{self.c_name}.{name} is not {width} byte(s): '
            f'gen_mapping_table.py assumes it is");'
            for field in self.fields
            for name, width in field.widths_asserted()
        ]

    def arrays(self, entry, ident):
        return [line for f in self.fields for line in f.arrays(entry, ident)]

    def row(self, entry, ident, indent="    "):
        lines = [indent + "{"]
        for field in self.fields:
            for name, value, note in field.inits(entry, ident):
                lines.append(
                    f"{indent}    .{name} = {value},{f' /* {note} */' if note else ''}"
                )
        lines.append(indent + "},")
        return lines

    def inline(self, entry, ident, suffix=""):
        """The entry as a one-line initialiser, for an element of a static array."""
        inits = [i for f in self.fields for i in f.inits(entry, ident)]
        text = "{" + ", ".join(f".{n} = {v}" for n, v, _ in inits) + "}" + suffix
        notes = [n for _, _, n in inits if n]
        return f"{text} /* {notes[0]} */" if notes else text

    def widths(self, entry, where, errors):
        for field in self.fields:
            try:
                field.widths(entry, where, errors)
            except (KeyError, ValueError, TypeError):
                pass  # malformed entry: the structural checks in validate() report it


def _startup(cap):
    return cap.get("startup", {})


def _bounds(cap):
    return cap.get("bounds_from", {})


def _comp_match(comp):
    return comp["matter_match"]


# What the generator must fill for each table type declared in rm_mirror_mapping.h:
# per field, where it reads from the JSON, how it renders, the range its width allows,
# and the width itself (asserted against the header). The C type, its comment and the
# field order live in the header - the engine reads these fields, so it owns their shape.
STRUCTS = {}

STRUCTS["cmd_arg"] = Struct(
    "rm_mirror_cmd_arg_t",
    [
        I32(
            "literal",
            lambda a: 0 if a["value"] == ARG_VALUE_PLACEHOLDER else a["value"],
        ),
        U8("field_id", lambda a: a["field"], note=lambda a: a.get("name", "")),
        Enum("type", lambda a: ARG_TYPES[a["type"]]),
        Flag("from_value", lambda a: a["value"] == ARG_VALUE_PLACEHOLDER),
    ],
)

STRUCTS["write_cmd"] = Struct(
    "rm_mirror_write_cmd_t",
    [
        Ref(
            "args",
            "const rm_mirror_cmd_arg_t",
            lambda c: c.get("args", []),
            None,
            "__cmd_args",
            "n_args",
        ),
        U32(
            "command_id",
            lambda c: parse_hex(c["command"]),
            render=_hex2,
            note=lambda c: c.get("name", ""),
        ),
        I32("when", lambda c: c.get("when", 0)),
        Flag("has_when", lambda c: "when" in c),
    ],
)

STRUCTS["shadow_attr"] = Struct(
    "rm_mirror_shadow_attr_t",
    [
        U32("attribute_id", lambda s: parse_hex(s["attribute"])),
        Enum("value_type", lambda s: VAL_TYPES[s["value_type"]]),
    ],
)

STRUCTS["capability"] = Struct(
    "rm_mirror_capability_t",
    [
        Str("param_type", lambda c: c["capability"]),
        U32("cluster_id", lambda c: parse_hex(attr_match(c)["cluster"])),
        U32("attribute_id", lambda c: parse_hex(attr_match(c)["attribute"])),
        Enum("value_type", lambda c: VAL_TYPES[attr_match(c)["value_type"]]),
        U32("feature_map", lambda c: feature_map(attr_match(c)), render=_hex8),
        Raw("xform", lambda c, ident: _xform_init(ident, c["transform"])),
        Ref(
            "write_cmds",
            "const rm_mirror_write_cmd_t",
            lambda c: c.get("write_as", {}).get("commands", []),
            None,
            "__write_cmds",
            "n_write_cmds",
        ),
        Ref(
            "seed_cmds",
            "const rm_mirror_write_cmd_t",
            lambda c: c.get("seed_as", {}).get("commands", []),
            None,
            "__seed_cmds",
            "n_seed_cmds",
        ),
        Arr(
            "shadow_attrs",
            "const rm_mirror_shadow_attr_t",
            lambda c: c.get("shadow_attributes", []),
            lambda s: STRUCTS["shadow_attr"].inline(s, ""),
            "__shadows",
            "n_shadow_attrs",
        ),
        Str("report_as", lambda c: c.get("report_as", {}).get("kind")),
        U32(
            "startup_attr",
            lambda c: parse_hex(_startup(c)["attribute"]) if _startup(c) else 0,
        ),
        Enum(
            "startup_policy",
            lambda c: (
                STARTUP_POLICIES[_startup(c)["policy"]]
                if _startup(c)
                else "RM_MIRROR_STARTUP_NONE"
            ),
        ),
        I32("startup_min", lambda c: _startup(c).get("min", 0)),
        Flag(
            "startup_skip_on_sw_update",
            lambda c: _startup(c).get("skip_on_software_update", False),
        ),
        Flag("deferred_persistence", lambda c: c.get("deferred_persistence", False)),
        U32(
            "bounds_min_attr",
            lambda c: bounds_attr(_bounds(c)["min"]) if "min" in _bounds(c) else 0,
        ),
        U32(
            "bounds_max_attr",
            lambda c: bounds_attr(_bounds(c)["max"]) if "max" in _bounds(c) else 0,
        ),
        Enum(
            "bounds_value_type",
            lambda c: VAL_TYPES[_bounds(c).get("value_type", "none")],
        ),
        Flag("node_scoped", lambda c: attr_match(c).get("node_scoped", False)),
        Flag("rule_gated", lambda c: c.get("rule_gated", False)),
    ],
)

STRUCTS["composite"] = Struct(
    "rm_mirror_composite_t",
    [
        Str("id", lambda c: c["id"]),
        Arr(
            "param_types",
            "const char *const",
            lambda c: c["params"],
            _quoted,
            "__comp_params",
            "n_params",
        ),
        U32("cluster_id", lambda c: parse_hex(_comp_match(c)["cluster"])),
        Arr(
            "attribute_ids",
            "const uint32_t",
            lambda c: [parse_hex(a) for a in _comp_match(c)["attributes"]],
            _hex4,
            "__comp_attrs",
            "n_attributes",
        ),
        Arr(
            "value_types",
            "const rm_mirror_val_type_t",
            lambda c: _comp_match(c)["value_types"],
            lambda t: VAL_TYPES[t],
            "__comp_val_types",
            None,
        ),
        U32("feature_map", lambda c: feature_map(_comp_match(c)), render=_hex8),
        Enum("conversion", lambda c: COMPOSITE_CONVERSIONS[c["conversion"]["type"]]),
        Flag("deferred_persistence", lambda c: c.get("deferred_persistence", False)),
    ],
)

STRUCTS["extra_devtype"] = Struct(
    "rm_mirror_extra_devtype_t",
    [
        U32("device_type_id", lambda d: parse_hex(d["id"])),
        U8("device_type_version", lambda d: d["version"]),
        Ref(
            "mandatory_clusters",
            "const uint32_t",
            lambda d: d.get("mandatory_clusters", []),
            None,
            "__rule_extra_clusters",
            "n_mandatory_clusters",
        ),
    ],
)

STRUCTS["devtype_rule"] = Struct(
    "rm_mirror_devtype_rule_t",
    [
        Arr(
            "param_types",
            "const char *const",
            lambda r: r["params"],
            _quoted,
            "__rule_params",
            "n_params",
        ),
        Arr(
            "optional_params",
            "const char *const",
            lambda r: r.get("optional_params", []),
            _quoted,
            "__rule_opt_params",
            "n_optional_params",
        ),
        U32("matter_device_type_id", lambda r: parse_hex(r["matter_device_type"])),
        U8("matter_device_type_version", lambda r: r["matter_device_type_version"]),
        Arr(
            "mandatory_clusters",
            "const uint32_t",
            lambda r: [parse_hex(c) for c in r.get("mandatory_clusters", [])],
            _hex4,
            "__rule_clusters",
            "n_mandatory_clusters",
        ),
        Ref(
            "extra_device_types",
            "const rm_mirror_extra_devtype_t",
            lambda r: r.get("additional_device_types", []),
            None,
            "__rule_extra",
            "n_extra_device_types",
        ),
    ],
)

STRUCTS["device_entry"] = Struct(
    "rm_mirror_device_entry_t",
    [
        Str("device_type", lambda e: e["device_type"]),
        Ref(
            "rules",
            "const rm_mirror_devtype_rule_t",
            lambda e: e["rules"],
            None,
            "__rules",
            "n_rules",
        ),
    ],
)


def _check_widths(mapping, errors):
    """The range checks the generated field widths imply, driven by the same
    descriptors that emit them - so a narrowed field cannot silently truncate."""
    for cap in mapping.get("capabilities", []):
        where = cap.get("capability", "<missing>")
        STRUCTS["capability"].widths(cap, where, errors)
        # The enum_map arrays are emitted by _xform_arrays, so no descriptor counts them:
        # rm_mirror_xform_t holds both lengths in a uint8_t.
        xform = cap.get("transform", {})
        if xform.get("type") == "enum_map":
            check_count(where, "enum_map map", len(xform.get("map", [])), errors)
            check_count(
                where,
                "enum_map matter_aliases",
                len(xform.get("matter_aliases", [])),
                errors,
            )
        for shadow in cap.get("shadow_attributes", []):
            STRUCTS["shadow_attr"].widths(shadow, where, errors)
        for key, _prefix, _suffix in CMD_KEYS:
            for i, cmd in enumerate(cap.get(key, {}).get("commands", [])):
                cmd_where = f"{where}: {key} command {i}"
                STRUCTS["write_cmd"].widths(cmd, cmd_where, errors)
                for arg in cmd.get("args", []):
                    STRUCTS["cmd_arg"].widths(arg, cmd_where, errors)
    for comp in mapping.get("composites", []):
        STRUCTS["composite"].widths(
            comp, f"composite {comp.get('id', '<missing>')}", errors
        )
    for entry in mapping.get("device_types", []):
        dev = entry.get("device_type", "<missing>")
        STRUCTS["device_entry"].widths(entry, dev, errors)
        for i, rule in enumerate(entry.get("rules", [])):
            rule_where = f"{dev} rule {i}"
            STRUCTS["devtype_rule"].widths(rule, rule_where, errors)
            for dt in rule.get("additional_device_types", []):
                STRUCTS["extra_devtype"].widths(dt, rule_where, errors)


def _any_seed_cmds(mapping):
    return any(
        cap.get("seed_as", {}).get("commands")
        for cap in mapping.get("capabilities", [])
    )


def emit_header(mapping, source_name):
    """The per-mapping half of the header: what this mapping needs compiled in, and the
    assertions tying the descriptors to the hand-written types."""
    lines = [GENERATED_BANNER.format(source=source_name)]
    lines.append("#ifndef __RM_MIRROR_MAPPING_GEN_H__")
    lines.append("#define __RM_MIRROR_MAPPING_GEN_H__")
    lines.append("")
    lines.append(f'#include "{TYPES_HEADER}"')
    lines.append("")
    lines.append(
        "/* Clusters this mapping needs the port to build. The port compiles in only the"
    )
    lines.append(" * matching factories (src/port/clusters/). */")
    for cid in port_clusters(mapping):
        lines.append(f"#define RM_MIRROR_USES_CLUSTER_{cid:04X} 1")
    lines.append("")
    lines.append(
        "/* Whether any capability declares a seed_as command, i.e. whether the engine has a"
    )
    lines.append(
        " * server holding its own copy of an attribute to seed after the reseed. */"
    )
    lines.append(
        f"#define RM_MIRROR_SEEDS_SHADOWS {1 if _any_seed_cmds(mapping) else 0}"
    )
    lines.append("")
    lines.append(
        "/* Engine vocabulary this mapping exercises: transforms, composite conversions"
    )
    lines.append(" * and startup policies. The engine compiles in only these. */")
    for macro in vocabulary_macros(mapping):
        lines.append(f"#define {macro} 1")
    lines.append("")
    lines.append(
        f"/* The table fields this generator fills, against the widths {TYPES_HEADER}"
    )
    lines.append(" * declares. A width changed there alone stops the build here. */")
    for struct in STRUCTS.values():
        lines += struct.assertions()
    lines.append("")
    lines.append("#endif /* __RM_MIRROR_MAPPING_GEN_H__ */")
    return "\n".join(lines) + "\n"


def port_clusters(mapping):
    """Clusters the port's factory must build for @p mapping, each with the union
    of the FeatureMap bits the mapping asks for.

    Node-scoped matches are left out: they bind on endpoint 0, whose clusters the
    Matter stack provides rather than the mirror's factory.
    """
    clusters = {}
    for cap in mapping["capabilities"]:
        match = attr_match(cap)
        if match.get("node_scoped", False):
            continue
        cid = parse_hex(match["cluster"])
        clusters[cid] = clusters.get(cid, 0) | feature_map(match)
    for comp in mapping["composites"]:
        cid = parse_hex(comp["matter_match"]["cluster"])
        clusters[cid] = clusters.get(cid, 0) | feature_map(comp["matter_match"])
    for entry in mapping["device_types"]:
        for rule in entry.get("rules", []):
            for cluster in rule.get("mandatory_clusters", []):
                clusters.setdefault(parse_hex(cluster), 0)
            for dt in rule.get("additional_device_types", []):
                for cluster in dt.get("mandatory_clusters", []):
                    clusters.setdefault(parse_hex(cluster), 0)
    return dict(sorted(clusters.items()))


def vocabulary_macros(mapping):
    """The engine vocabulary this mapping exercises, as macro names.

    The engine gates its per-transform / per-conversion / per-startup-policy
    code on these, so a profile that never asks for (say) the hue/saturation to
    XY conversion does not carry the colour maths.
    """
    macros = []
    xforms = {c["transform"]["type"] for c in mapping["capabilities"]}
    for name in sorted(xforms):
        macros.append(
            f"RM_MIRROR_USES_XFORM_{XFORM_TYPES[name][len('RM_MIRROR_XFORM_') :]}"
        )
    if mapping["composites"]:
        macros.append("RM_MIRROR_USES_COMPOSITES")
    for conv in sorted({c["conversion"]["type"] for c in mapping["composites"]}):
        macros.append(
            f"RM_MIRROR_USES_CONV_{COMPOSITE_CONVERSIONS[conv][len('RM_MIRROR_COMPOSITE_CONV_') :]}"
        )
    policies = {
        c["startup"]["policy"] for c in mapping["capabilities"] if "startup" in c
    }
    for policy in sorted(policies):
        macros.append(
            f"RM_MIRROR_USES_STARTUP_{STARTUP_POLICIES[policy][len('RM_MIRROR_STARTUP_') :]}"
        )
    return macros


def emit_cluster_check(mapping, source_name, allow_external):
    """Emit the port cross-check: every cluster the mapping needs must have a
    factory in the port, or the build fails naming the cluster.

    Included by the port after its per-cluster factories have defined their
    RM_MIRROR_PORT_HAS_CLUSTER_* markers, so this cannot live in the mapping
    header. With @p allow_external the product promises a runtime factory
    (esp_rmaker_matter_mirror_register_cluster_factory), so the check is
    reduced to a record of what is expected.
    """
    lines = [GENERATED_BANNER.format(source=source_name)]
    lines.append("#ifndef __RM_MIRROR_CLUSTER_CHECK_GEN_H__")
    lines.append("#define __RM_MIRROR_CLUSTER_CHECK_GEN_H__")
    lines.append("")
    if allow_external:
        lines.append(
            "/* Cluster factories may be registered at runtime, so a missing one is not a build error. */"
        )
    for cid in port_clusters(mapping):
        if allow_external:
            lines.append(f"/* cluster 0x{cid:04X} */")
            continue
        lines.append(f"#if !defined(RM_MIRROR_PORT_HAS_CLUSTER_{cid:04X})")
        lines.append(
            f'#error "Matter mirror: the mapping needs cluster 0x{cid:04X}, which the port cannot build. '
            f"Add a factory under src/port/clusters/, or register one at runtime and enable "
            f'CONFIG_ESP_RMAKER_NEO_MATTER_MIRROR_EXTERNAL_CLUSTERS."'
        )
        lines.append("#endif")
    lines.append("")
    lines.append("#endif /* __RM_MIRROR_CLUSTER_CHECK_GEN_H__ */")
    return "\n".join(lines) + "\n"


def _c_ident(text):
    return text.replace(".", "_").replace("-", "_")


def _xform_init(ident, xform):
    """The rm_mirror_xform_t initialiser for @p xform: type, plus the one union arm
    the type names. Identity and kelvin/mireds carry no payload."""
    kind = xform["type"]
    parts = [f".type = {XFORM_TYPES[kind]}"]
    if kind == "linear":
        parts.append(
            ".u.linear = {%d, %d, %d, %d}"
            % (xform["in_min"], xform["in_max"], xform["out_min"], xform["out_max"])
        )
    elif kind == "string":
        parts.append(f".u.scalar = {xform['max_len']}")
    elif kind == "scale":
        parts.append(f".u.scalar = {xform['factor']}")
    elif kind == "enum_map":
        aliases = xform.get("matter_aliases", [])
        aliases_ref = f"__aliases_{ident}" if aliases else "NULL"
        parts.append(f".n_pairs = {len(xform['map'])}")
        parts.append(f".n_aliases = {len(aliases)}")
        parts.append(f".u.enum_map = {{__pairs_{ident}, {aliases_ref}}}")
    return "{" + ", ".join(parts) + "}"


def _xform_arrays(cap, ident):
    """The enum_map pair arrays the transform union points at."""
    xform = cap["transform"]
    if xform["type"] != "enum_map":
        return []

    def pairs(items):
        return ", ".join(f"{{{p['rmng']}, {p['matter']}}}" for p in items)

    lines = [
        f"static const rm_mirror_enum_pair_t __pairs_{ident}[] = {{{pairs(xform['map'])}}};"
    ]
    aliases = xform.get("matter_aliases", [])
    if aliases:
        lines.append(
            f"static const rm_mirror_enum_pair_t __aliases_{ident}[] = {{{pairs(aliases)}}};"
        )
    return lines


def _cmd_arrays(cap, ident):
    """A capability's command payloads: one arg array per command, then the command
    array itself. Hand-emitted because each command carries an array of its own."""
    lines = []
    for key, cmds_prefix, suffix in CMD_KEYS:
        commands = cap.get(key, {}).get("commands", [])
        if not commands:
            continue
        for i, cmd in enumerate(commands):
            args = cmd.get("args", [])
            if not args:
                continue
            lines.append(
                f"static const rm_mirror_cmd_arg_t __cmd_args_{ident}{suffix}_{i}[] = {{"
            )
            lines += [f"    {STRUCTS['cmd_arg'].inline(arg, '', ',')}" for arg in args]
            lines.append("};")
        lines.append(f"static const rm_mirror_write_cmd_t {cmds_prefix}_{ident}[] = {{")
        for i, cmd in enumerate(commands):
            lines += STRUCTS["write_cmd"].row(cmd, f"{ident}{suffix}_{i}")
        lines.append("};")
    return lines


def _rule_arrays(entry, dev_ident):
    """A device type's rule arrays, and the extra-device-type arrays they point at."""
    lines = []
    for i, rule in enumerate(entry["rules"]):
        rid = f"{dev_ident}_{i}"
        lines += STRUCTS["devtype_rule"].arrays(rule, rid)
        extra = rule.get("additional_device_types", [])
        for j, dt in enumerate(extra):
            clusters = dt.get("mandatory_clusters", [])
            if clusters:
                vals = ", ".join(_hex4(parse_hex(c)) for c in clusters)
                lines.append(
                    f"static const uint32_t __rule_extra_clusters_{rid}_{j}[] = {{{vals}}};"
                )
        if extra:
            lines.append(
                f"static const rm_mirror_extra_devtype_t __rule_extra_{rid}[] = {{"
            )
            lines += [
                f"    {STRUCTS['extra_devtype'].inline(dt, f'{rid}_{j}', ',')}"
                for j, dt in enumerate(extra)
            ]
            lines.append("};")
    lines.append(f"static const rm_mirror_devtype_rule_t __rules_{dev_ident}[] = {{")
    for i, rule in enumerate(entry["rules"]):
        lines += STRUCTS["devtype_rule"].row(rule, f"{dev_ident}_{i}")
    lines.append("};")
    return lines


def _table(c_name, symbol, desc, entries, ident_of):
    """A top-level table and its count."""
    lines = [f"const {c_name} {symbol}[] = {{"]
    for entry in entries:
        lines += desc.row(entry, ident_of(entry))
    lines.append("};")
    lines.append(
        f"const size_t {symbol.replace('rm_mirror_', 'rm_mirror_n_', 1)} = "
        f"sizeof({symbol}) / sizeof({symbol}[0]);"
    )
    return lines


def emit_source(mapping, source_name, header_name):
    lines = [GENERATED_BANNER.format(source=source_name)]
    lines.append(f'#include "{header_name}"')
    lines.append("")
    lines.append(
        f'const char *const rm_mirror_mapping_version = "{mapping["mapping_version"]}";'
    )
    lines.append("")

    for cap in mapping["capabilities"]:
        ident = _c_ident(cap["capability"])
        lines += _xform_arrays(cap, ident)
        lines += STRUCTS["capability"].arrays(cap, ident)
        lines += _cmd_arrays(cap, ident)
    lines.append("")
    lines += _table(
        "rm_mirror_capability_t",
        "rm_mirror_capabilities",
        STRUCTS["capability"],
        mapping["capabilities"],
        lambda c: _c_ident(c["capability"]),
    )
    lines.append("")

    composites = mapping.get("composites", [])
    for comp in composites:
        lines += STRUCTS["composite"].arrays(comp, _c_ident(comp["id"]))
    if composites:
        lines.append("")
        lines += _table(
            "rm_mirror_composite_t",
            "rm_mirror_composites",
            STRUCTS["composite"],
            composites,
            lambda c: _c_ident(c["id"]),
        )
    else:
        # ISO C forbids empty arrays/initializers; emit one zeroed entry, count 0.
        lines.append("const rm_mirror_composite_t rm_mirror_composites[1] = {{0}};")
        lines.append("const size_t rm_mirror_n_composites = 0;")
    lines.append("")

    for entry in mapping["device_types"]:
        lines += _rule_arrays(entry, _c_ident(entry["device_type"]))
    lines.append("")
    lines += _table(
        "rm_mirror_device_entry_t",
        "rm_mirror_device_entries",
        STRUCTS["device_entry"],
        mapping["device_types"],
        lambda e: _c_ident(e["device_type"]),
    )
    return "\n".join(lines) + "\n"


def emit_vectors_c(vectors_json, source_name):
    """The golden vectors as C tables, for consumers whose tests would rather not parse JSON at
    runtime (firmware POSIX tests). Same content as --output-vectors; commit both."""
    v = json.loads(vectors_json)
    L = [
        GENERATED_BANNER.format(source=source_name),
        "#ifndef __RM_MIRROR_VECTORS_GEN_H__",
        "#define __RM_MIRROR_VECTORS_GEN_H__",
        "",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        f'#define RM_MIRROR_VECTORS_MAPPING_VERSION "{v["mapping_version"]}"',
        f"#define RM_MIRROR_VEC_MAX_VALS {VEC_MAX_VALS}",
        "",
        "typedef struct {",
        "    int32_t in;",
        "    int32_t out;",
        "} rm_mirror_vec_scalar_t;",
        "typedef struct {",
        "    int32_t in[RM_MIRROR_VEC_MAX_VALS];",
        "    int32_t out[RM_MIRROR_VEC_MAX_VALS];",
        "} rm_mirror_vec_pair_t;",
        "typedef struct {",
        "    const char *param_type;      /* capability the transform belongs to */",
        "    const char *transform_type;  /* enumerated kind, for RM_MIRROR_USES_* gating in the test */",
        "    const rm_mirror_vec_scalar_t *to_matter; size_t n_to_matter;",
        "    const rm_mirror_vec_scalar_t *to_rmng;   size_t n_to_rmng;",
        "} rm_mirror_vec_transform_t;",
        "typedef struct {",
        "    const char *id; const char *conversion;",
        "    uint8_t n_params;      /* values per rmng-domain side of a row */",
        "    uint8_t n_attributes;  /* values per matter-domain side of a row */",
        "    const rm_mirror_vec_pair_t *to_matter; size_t n_to_matter;",
        "    const rm_mirror_vec_pair_t *to_rmng;   size_t n_to_rmng;",
        "} rm_mirror_vec_composite_t;",
        "",
    ]
    for i, t in enumerate(v["transforms"]):
        L.append(
            f"static const rm_mirror_vec_scalar_t __vec_t{i}_m[] = {{"
            + ", ".join(f"{{{a}, {b}}}" for a, b in t["to_matter"])
            + "};"
        )
        L.append(
            f"static const rm_mirror_vec_scalar_t __vec_t{i}_r[] = {{"
            + ", ".join(f"{{{a}, {b}}}" for a, b in t["to_rmng"])
            + "};"
        )
    L.append("static const rm_mirror_vec_transform_t rm_mirror_vec_transforms[] = {")
    for i, t in enumerate(v["transforms"]):
        L.append(
            f'    {{"{t["capability"]}", "{t["transform"]["type"]}", __vec_t{i}_m, {len(t["to_matter"])}, __vec_t{i}_r, {len(t["to_rmng"])}}},'
        )
    L.append("};")
    L.append(
        "static const size_t rm_mirror_n_vec_transforms = sizeof(rm_mirror_vec_transforms) / sizeof(rm_mirror_vec_transforms[0]);"
    )
    L.append("")

    def _row(where, side_a, side_b):
        for side in (side_a, side_b):
            if len(side) > VEC_MAX_VALS:
                raise ValueError(
                    f"{where}: a vector row carries {len(side)} values, more than "
                    f"RM_MIRROR_VEC_MAX_VALS ({VEC_MAX_VALS})"
                )
        return (
            "{{"
            + ", ".join(map(str, side_a))
            + "}, {"
            + ", ".join(map(str, side_b))
            + "}}"
        )

    for i, c in enumerate(v["composites"]):
        L.append(
            f"static const rm_mirror_vec_pair_t __vec_c{i}_m[] = {{"
            + ", ".join(_row(c["id"], a, b) for a, b in c["to_matter"])
            + "};"
        )
        L.append(
            f"static const rm_mirror_vec_pair_t __vec_c{i}_r[] = {{"
            + ", ".join(_row(c["id"], a, b) for a, b in c["to_rmng"])
            + "};"
        )
    if v["composites"]:
        L.append(
            "static const rm_mirror_vec_composite_t rm_mirror_vec_composites[] = {"
        )
        for i, c in enumerate(v["composites"]):
            L.append(
                f'    {{"{c["id"]}", "{c["conversion"]}", {len(c["params"])}, '
                f"{len(c['attributes'])}, __vec_c{i}_m, {len(c['to_matter'])}, "
                f"__vec_c{i}_r, {len(c['to_rmng'])}}},"
            )
        L.append("};")
        L.append(
            "static const size_t rm_mirror_n_vec_composites = sizeof(rm_mirror_vec_composites) / sizeof(rm_mirror_vec_composites[0]);"
        )
    else:
        L.append(
            "static const rm_mirror_vec_composite_t rm_mirror_vec_composites[1] = {{0}};"
        )
        L.append("static const size_t rm_mirror_n_vec_composites = 0;")
    L += ["", "#endif /* __RM_MIRROR_VECTORS_GEN_H__ */"]
    return "\n".join(L) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--lib",
        required=True,
        action="append",
        metavar="PATH",
        help="library JSON file: capabilities, composites and device-type rules (repeatable)",
    )
    parser.add_argument(
        "--profile",
        metavar="PATH",
        help="profile JSON file naming the device types to compile in",
    )
    parser.add_argument("--output-c", help="generated C source path")
    parser.add_argument("--output-h", help="generated C header path")
    parser.add_argument(
        "--output-check",
        help="generated port cross-check header path",
    )
    parser.add_argument(
        "--vectors-in",
        metavar="PATH",
        help="golden vectors JSON copied from the mapping repo (see mapping/vectors/)",
    )
    parser.add_argument(
        "--output-vectors-c",
        metavar="PATH",
        help="the golden vectors lowered to a C header, for the POSIX tests",
    )
    parser.add_argument(
        "--allow-external-clusters",
        action="store_true",
        help="a cluster with no compiled-in factory is not a build error: the "
        "application registers one at runtime",
    )
    args = parser.parse_args(argv)

    c_outputs = (args.output_c, args.output_h, args.output_check)
    if any(c_outputs) and not all(c_outputs):
        parser.error("--output-c, --output-h and --output-check go together")
    if any(c_outputs) and not args.profile:
        parser.error("--profile is required to generate C tables")
    if bool(args.vectors_in) != bool(args.output_vectors_c):
        parser.error("--vectors-in and --output-vectors-c go together")
    if not any(c_outputs) and not args.output_vectors_c:
        parser.error(
            "nothing to do: give --output-c/-h/--output-check or --output-vectors-c"
        )

    lib_name = ", ".join(Path(p).name for p in args.lib)

    # The vectors are library-level and already validated upstream: lower the committed copy
    # rather than recompute it, so the golden data stays golden.
    if args.output_vectors_c:
        vectors = Path(args.vectors_in).read_text(encoding="utf-8")
        Path(args.output_vectors_c).write_text(
            emit_vectors_c(vectors, Path(args.vectors_in).name), encoding="utf-8"
        )
    if not any(c_outputs):
        return 0

    library, errors = load_library(args.lib)
    if errors:
        return report(errors, PROG)

    # Validate the whole library, so rot in an entry no profile selects still fails the
    # build rather than waiting for the product that needs it.
    errors = validate(library, [_check_widths])
    if errors:
        return report(errors, PROG)

    profile = json.loads(Path(args.profile).read_text(encoding="utf-8"))
    mapping, errors = resolve(library, profile)
    if errors:
        return report(errors, f"{PROG}: {Path(args.profile).name}")
    errors = validate(mapping, [_check_widths])
    if errors:
        return report(errors, PROG)

    source_name = f"{lib_name} (profile: {profile.get('name', '?')})"
    Path(args.output_h).write_text(emit_header(mapping, source_name), encoding="utf-8")
    Path(args.output_c).write_text(
        emit_source(mapping, source_name, TYPES_HEADER), encoding="utf-8"
    )
    Path(args.output_check).write_text(
        emit_cluster_check(mapping, source_name, args.allow_external_clusters),
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
